# Homework 2 Prob 6. 

***Double Click here to edit this cell***

- Name: 임태호
- Student ID: 201903021
- Submission date: 2023.04.12

# You must run this homework code on Google Colab

- DON'T run on Google Colab Pro
- DON'T use GPU or TPU

## Remark. If any kind of loops including for-loop, while-loops, list comprehension, and other loops are found, you get no points (0점). 

## Use numpy wherever it is possible. 


## Total: 30 pts

### You must run the following two cells to make sure you are running on Google Colab

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2200.142
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4400.28
clflush size	: 64
cache_alignment	: 64
addres

In [ ]:
!cat /proc/meminfo

MemTotal:       13297192 kB
MemFree:         8763060 kB
MemAvailable:   12427480 kB
Buffers:          155800 kB
Cached:          3679124 kB
SwapCached:            0 kB
Active:           348280 kB
Inactive:        3961852 kB
Active(anon):       1068 kB
Inactive(anon):   466332 kB
Active(file):     347212 kB
Inactive(file):  3495520 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:             14704 kB
Writeback:             0 kB
AnonPages:        475444 kB
Mapped:           249900 kB
Shmem:              1348 kB
KReclaimable:     126280 kB
Slab:             155536 kB
SReclaimable:     126280 kB
SUnreclaim:        29256 kB
KernelStack:        4208 kB
PageTables:         6168 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6648596 kB
Committed_AS:    2639692 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        9060 kB
VmallocChunk:          0 kB
Percpu:          

## Problem 6 (20 pts)

- **find_k_nearest_index_big** returns the index of the k-nearest for 50 million data
- We want to time the execution
- *Do not use sklearn, scipy or any module computing k-nearest points directly*
- Use numpy functions only

In [ ]:
# import part here
import numpy as np

def find_k_nearest_index_big(data, center, k):
    n, d = data.shape

    if n <= 10000:  # base case
        distances = np.sum((data - center) ** 2, axis=1)
        indices = np.argpartition(distances, k)[:k]
        return indices

    # divide the data into two halves
    half = n // 2
    left_data, right_data = data[:half], data[half:]

    # find the k-nearest neighbors in the left and right halves
    left_indices = find_k_nearest_index_big(left_data, center, k)
    right_indices = find_k_nearest_index_big(right_data, center, k)

    # merge the indices and recompute the distances
    indices = np.concatenate([left_indices, right_indices])
    distances = np.sum((data[indices] - center) ** 2, axis=1)
    indices = indices[np.argpartition(distances, k)[:k]]

    return indices



In [ ]:
# DO NOT EDIT THIS CELL

import time

np.random.seed(100)
data = np.random.randn(30000000,20)   # 30 million data
k = 5
center = np.random.randn(20)
start = time.time()
print(find_k_nearest_index_big(data, center, k))
end = time.time()

lapse = end - start
total = 10
weight = 1.5
grace = 20
my_point = int(total / (weight ** (lapse // grace)))
print(f'Total time taken : {lapse} seconds')
print(f'My point is {my_point}')

[1172  351 5821 2067 4751]
Total time taken : 3.3390402793884277 seconds
My point is 10


**Your time must be around:**
```
[ _____________________________________________ ]
Total time taken : 5.2564404010772705 seconds
My point is 10
```

In [ ]:
# DO NOT EDIT THIS CELL

import time

np.random.seed(100)
data = np.random.randn(50000000,20)   # 50 million data
k = 5
center = np.random.randn(20)
start = time.time()
print(find_k_nearest_index_big(data, center, k))
end = time.time()

lapse = end - start
total = 10
weight = 1.5
grace = 20
my_point = int(total / (weight ** (lapse // grace)))
print(f'Total time taken : {lapse} seconds')
print(f'My point is {my_point}')

[5488 2097 1964 3045 3254]
Total time taken : 8.585269212722778 seconds
My point is 10


**Your time must be around:**
```
[ _____________________________________________ ]
Total time taken : 9.744923830032349 seconds
My point is 10
```

In [ ]:
# DO NOT EDIT THIS CELL

import time

np.random.seed(100)
data = np.random.randn(70000000,20)   # 70 million data
k = 5
center = np.random.randn(20)
start = time.time()
print(find_k_nearest_index_big(data, center, k))
end = time.time()

lapse = end - start
total = 10
weight = 1.5
grace = 40
my_point = int(total / (weight ** (lapse // grace)))
print(f'Total time taken : {lapse} seconds')
print(f'My point is {my_point}')

[5248  836 7953 8414   97]
Total time taken : 14.864856719970703 seconds
My point is 10


**Your time must be around:**
```
[ _____________________________________________ ]
Total time taken : 20.60638999938965 seconds
My point is 10
```

## Ethics:
If you cheat, you will get negatgive of the total points.
If the homework total is 22 and you cheat, you get -22.

## What to submit

- Run **all cells** after restarting the kernel
- Goto "File -> Print Preview"
- Print the page as pdf
- Submit the pdf file in google classroom
- Pdf file name must be in a form of: homework_2_prob6_홍길동_202300001.pdf
- No late homeworks will be accepted
- Your homework will be graded on the basis of correctness, performance, and programming skills